version: "3.9"

services:
  streamlit-app:
    container_name: smile-streamlit
    image: streamlit-app:latest  # ✅ 使用已存在的映像
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    restart: unless-stopped
